/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* API ENDPOINTS */
export const API_CREATE_ACCOUNT = 'auth/register';
export const API_LOGIN = 'auth/login';
export const API_CURRENT_ACCOUNT = 'account/me';
export const API_LIST_PACKAGES = 'packages/list';
export const API_ACTIVE_SUBSCRIPTION = 'packages/subscription';
export const API_MY_REFERRAL_COUNT = 'account/referral-count';
export const API_MY_DAILY_EARNINGS = 'account/daily-earnings';
export const API_UPDATE_PROFILE = 'account/update';

/* AUTH */
export const USER_TOKEN_KEY = 'userToken';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REFRESH_USER_INFO = 'REFRESH_USER_INFO';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* APP DATA */
export const APP_GET_PACKAGES = 'APP_GET_PACKAGES';
export const APP_GET_PACKAGES_SUCCESS = 'APP_GET_PACKAGES_SUCCESS';
export const APP_GET_PACKAGES_ERROR = 'APP_GET_PACKAGES_ERROR';

export const APP_GET_ACTIVE_SUBSCRIPTION = 'APP_GET_ACTIVE_SUBSCRIPTION';
export const APP_GET_ACTIVE_SUBSCRIPTION_SUCCESS =
  'APP_GET_ACTIVE_SUBSCRIPTION_SUCCESS';
export const APP_GET_ACTIVE_SUBSCRIPTION_ERROR =
  'APP_GET_ACTIVE_SUBSCRIPTION_ERROR';
export const APP_SET_NO_ACTIVE_SUBSCRIPTION = 'APP_SET_NO_ACTIVE_SUBSCRIPTION';

export const APP_MY_REFERRAL_COUNT = 'APP_MY_REFERRAL_COUNT';
export const APP_MY_REFERRAL_COUNT_SUCCESS = 'APP_MY_REFERRAL_COUNT_SUCCESS';
export const APP_MY_REFERRAL_COUNT_ERROR = 'APP_MY_REFERRAL_COUNT_ERROR';

export const APP_GET_RECENT_EARNINGS = 'APP_GET_RECENT_EARNINGS';
export const APP_GET_RECENT_EARNINGS_SUCCESS =
  'APP_GET_RECENT_EARNINGS_SUCCESS';
export const APP_GET_RECENT_EARNINGS_ERROR = 'APP_GET_RECENT_EARNINGS_ERROR';

export const APP_UPDATE_PROFILE = 'APP_UPDATE_PROFILE';
export const APP_UPDATE_PROFILE_SUCCESS = 'APP_UPDATE_PROFILE_SUCCESS';
export const APP_UPDATE_PROFILE_ERROR = 'APP_UPDATE_PROFILE_ERROR';

// WEB3
export const APP_WEB3_LOGIN_ID = 'APP_WEB3_LOGIN_ID'

